version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: indiga_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  bot:
    build: .
    container_name: indiga_bot
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?schema=public
      - CHANNEL_USERNAME=${CHANNEL_USERNAME}
      - GROUP_LINK=${GROUP_LINK}
      - GROUP_CHAT_ID=${GROUP_CHAT_ID}
    restart: unless-stopped

volumes:
  postgres_data: